import Navigation from "./components/Navigation";
import "../styles/Global.css";
import Footer from "./components/Footer";


import { Belleza } from "next/font/google";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export const akshar = Belleza({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin-ext"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <header>
        <title>PioPio</title>
       
      </header>
      <body className={akshar.className}>
        <Navigation />

        {children}
        <Footer />
      </body>
    </html>
  );
}
